### ISSUE TITLE
Add support for Stata for 3.2 output

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/Extract2DDI#19]

**Comment by spuddybike** [comment]
For DataItem,. attribute values are not correctly populated

                    <ddi1:DataItem>
                        <r:VariableReference>
                            <r:URN typeOfIdentifier="Canonical">urn:ddi:uk.closer:e9b94a1b-797c-4f89-bf1c-09bf25492359:1</r:URN>
                            <r:TypeOfObject>Variable</r:TypeOfObject>
                        </r:VariableReference>
                        <r:ProprietaryInfo>
                            <r:ProprietaryProperty>
                                <r:AttributeKey>Width</r:AttributeKey>
                                <r:AttributeValue>???</r:AttributeValue>
                            </r:ProprietaryProperty>
                            <r:ProprietaryProperty>
                                <r:AttributeKey>Decimals</r:AttributeKey>
                                <r:AttributeValue>???</r:AttributeValue>
                            </r:ProprietaryProperty>
                            <r:ProprietaryProperty>
                                <r:AttributeKey>WriteFormatType</r:AttributeKey>
                                <r:AttributeValue>???</r:AttributeValue>
                            </r:ProprietaryProperty>
                        </r:ProprietaryInfo>
                    </ddi1:DataItem>

**Comment by alkondrashov** [comment]
@spuddybike , I managed to generate STATA 3.2 with the following command:
java -jar target/Extract2DDI.jar -f src/test/resources/test-file-data-types.dta --format 3.2

I'm sending you the result file over the email.
