### ISSUE TITLE
Add optional citation to 3.2 Format

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/Extract2DDI#23]
Add configuration option in config file to add blank citation
After DDIInstance / URN
After ResourcePackage / URN
After PhysicalInstance / URN
    <r:Citation>
          <r:Title><r:String xml:lang="en-GB"></r:String></r:Title>
          <r:AlternateTitle><r:String xml:lang="en-GB"></r:String></r:AlternateTitle>
        </r:Citation>

**Comment by alkondrashov** [comment]
@spuddybike , just to confirm, is this what is needed?

<img width="977" alt="Screenshot 2024-03-11 at 19 56 26" src="https://github.com/CLOSER-Cohorts/Extract2DDI/assets/4246666/e9c05c5d-dd14-4fb0-aca3-25aa44219850">

**Comment by alkondrashov** [comment]
How would it look in the config file?

Currently the config file looks like this:
```
agency=uk.closer
ddilang=en-GB
stats=max,min,valid,invalid,freq,stdev
outputfile=test-file-stata-3.2
sumstats=TRUE
```

**Comment by spuddybike** [comment]
[bib_07_pbq.ddi32.rp.txt](https://github.com/CLOSER-Cohorts/Extract2DDI/files/14639764/bib_07_pbq.ddi32.rp.txt)
Example of output with citation
