### ISSUE TITLE
DataItem attribute values not populated correctly from SPSS 3.2 output

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/Extract2DDI#28]
see https://github.com/ncrncornell/ced2arspssreader/blob/master/src/edu/cornell/ncrn/ced2ar/data/spss/SPSSVariable.java line 414 onwards

Currently have ??? should be valid entries

**Comment by alkondrashov** [comment]
Hi @spuddybike , do you have file that definitely contains attribute values? I'm getting null as the attribute map

**Comment by spuddybike** [comment]
<ddi1:DataItem>
            <r:VariableReference>
              <r:URN typeOfIdentifier="Canonical">urn:ddi:uk.bib:Cak93XHWKKbuy29B:1.0.0</r:URN>
              <r:TypeOfObject>Variable</r:TypeOfObject>
            </r:VariableReference>
            <ddi1:ProprietaryDataType>A</ddi1:ProprietaryDataType>
            <ddi1:ProprietaryOutputFormat>A8</ddi1:ProprietaryOutputFormat>
            <r:ProprietaryInfo>
              <r:ProprietaryProperty>
                <r:AttributeKey>Width</r:AttributeKey>
                <r:AttributeValue>8</r:AttributeValue>
              </r:ProprietaryProperty>
              <r:ProprietaryProperty>
                <r:AttributeKey>Decimals</r:AttributeKey>
                <r:AttributeValue>0</r:AttributeValue>
              </r:ProprietaryProperty>
              <r:ProprietaryProperty>
                <r:AttributeKey>WriteFormatType</r:AttributeKey>
                <r:AttributeValue>1</r:AttributeValue>
              </r:ProprietaryProperty>
            </r:ProprietaryInfo>
          </ddi1:DataItem>
