### ISSUE TITLE
Duplicate VariableStatistics IDs in 3.3. output

### ISSUE THREAD

**Issue by mr16165** [CLOSER-Cohorts/Extract2DDI#31]
For all variables, the corresponding VariableStatistics element has the same ID as the variable. In the example attached, variable 5a99caa4-6044-41d1-b7cc-cc94f1ae0e9c has a corresponding VariableStatistics element with the same ID. This element then has a VariableReference with the same correct
[lfsp_jm15_eul_11.sav.xml.txt](https://github.com/CLOSER-Cohorts/Extract2DDI/files/11721659/lfsp_jm15_eul_11.sav.xml.txt)
 ID

**Comment by spuddybike** [comment]
@alkondrashov could you add a unit test for this
