### ISSUE TITLE
Mandatory items

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/Extract2DDI#4]
For 3.2. and 3.3, 
-  f - filename
- agency
- ddilang
- format (3.2.or 3.3
For 2.5
- filename
- format (2.5)
-

**Comment by alkondrashov** [comment]
This is the message if either Agency or DDI language is required:

`>> java -jar target/Extract2DDI.jar -f src/test/resources/available_biological_samples.sav --config src/test/resources/config.txt --format 3.2`

`Agency is required...`

`DDI language is required...`
